import Head from "next/head";

import {Sevillana} from 'next/font/google'
import {Button, Card, Form} from "react-bootstrap";

const font=Sevillana({
  subsets: ['latin'],
  weight: '400'
})
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={`${font.className}`}>
        <div className={"d-flex justify-content-center align-items-center min-vh-100 min-vw-100"}>
          <Card style={{width: '400px'}} className={"shadow border-bottom-2 border-accent rounded-bottom-5 rounded-top-0"}>
            <Card.Header className={"bg-primary text-white rounded-top-0"}>Email Form</Card.Header>
            <Card.Body>
              <Form className="d-flex flex-column">
                <Form.Group controlId="formBasicEmail" >
                  <Form.Label>Email address</Form.Label>
                  <Form.Control type="email" placeholder="Enter email" />
                  <Form.Text>
                    Please enter your email.
                  </Form.Text>
                </Form.Group>
                <Button variant="primary" className={"accent-hover"} type="submit">
                  Submit
                </Button>
              </Form>
            </Card.Body>
          </Card>

        </div>

      </main>
    </>
  );
}
